import { Inter, Days_One } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "./Components/Common/context/GlobabStateProvider";

const daysOne = Days_One({ subsets: ["latin"], weight: "400" });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalStateProvider>
      <html lang="en">
        <body className={`${daysOne.className} bg-amber-100`}>{children}</body>
      </html>
    </GlobalStateProvider>
  );
}
