const initialBoard = [
  [
    { piece: "♖", row: 1, column: "a" },
    { piece: "♘", row: 1, column: "b" },
    { piece: "♗", row: 1, column: "c" },
    { piece: "♕", row: 1, column: "d" },
    { piece: "♔", row: 1, column: "e" },
    { piece: "♗", row: 1, column: "f" },
    { piece: "♘", row: 1, column: "g" },
    { piece: "♖", row: 1, column: "h" },
  ],
  [
    { piece: "♙", row: 2, column: "a" },
    { piece: "♙", row: 2, column: "b" },
    { piece: "♙", row: 2, column: "c" },
    { piece: "♙", row: 2, column: "d" },
    { piece: "♙", row: 2, column: "e" },
    { piece: "♙", row: 2, column: "f" },
    { piece: "♙", row: 2, column: "g" },
    { piece: "♙", row: 2, column: "h" },
  ],
  [
    { piece: "", row: 3, column: "a" },
    { piece: "", row: 3, column: "b" },
    { piece: "", row: 3, column: "c" },
    { piece: "", row: 3, column: "d" },
    { piece: "", row: 3, column: "e" },
    { piece: "", row: 3, column: "f" },
    { piece: "", row: 3, column: "g" },
    { piece: "", row: 3, column: "h" },
  ],
  [
    { piece: "", row: 4, column: "a" },
    { piece: "", row: 4, column: "b" },
    { piece: "", row: 4, column: "c" },
    { piece: "", row: 4, column: "d" },
    { piece: "", row: 4, column: "e" },
    { piece: "", row: 4, column: "f" },
    { piece: "", row: 4, column: "g" },
    { piece: "", row: 4, column: "h" },
  ],
  [
    { piece: "", row: 5, column: "a" },
    { piece: "", row: 5, column: "b" },
    { piece: "", row: 5, column: "c" },
    { piece: "", row: 5, column: "d" },
    { piece: "", row: 5, column: "e" },
    { piece: "", row: 5, column: "f" },
    { piece: "", row: 5, column: "g" },
    { piece: "", row: 5, column: "h" },
  ],
  [
    { piece: "", row: 6, column: "a" },
    { piece: "", row: 6, column: "b" },
    { piece: "", row: 6, column: "c" },
    { piece: "", row: 6, column: "d" },
    { piece: "", row: 6, column: "e" },
    { piece: "", row: 6, column: "f" },
    { piece: "", row: 6, column: "g" },
    { piece: "", row: 6, column: "h" },
  ],
  [
    { piece: "♟︎", row: 7, column: "a" },
    { piece: "♟︎", row: 7, column: "b" },
    { piece: "♟︎", row: 7, column: "c" },
    { piece: "♟︎", row: 7, column: "d" },
    { piece: "♟︎", row: 7, column: "e" },
    { piece: "♟︎", row: 7, column: "f" },
    { piece: "♟︎", row: 7, column: "g" },
    { piece: "♟︎", row: 7, column: "h" },
  ],
  [
    { piece: "♜", row: 8, column: "a" },
    { piece: "♞", row: 8, column: "b" },
    { piece: "♝", row: 8, column: "c" },
    { piece: "♛", row: 8, column: "d" },
    { piece: "♚", row: 8, column: "e" },
    { piece: "♝", row: 8, column: "f" },
    { piece: "♞", row: 8, column: "g" },
    { piece: "♜", row: 8, column: "h" },
  ],
];

module.exports = initialBoard;
